#!/bin/bash

# Terminal Colours
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;34m'
CYAN='\033[0;36m'
GREY='\033[0;90m'
NC='\033[0m' # No Color

BINPATH="/usr/local/bin"

/usr/bin/find ~/scripts__tools/scripts -name \*.sh -print0 | while read -d $'\0' ABSOLUTEPATH
do

    BASENAME=${ABSOLUTEPATH##*/}
    MINUS_EXT="${BASENAME%.*}"
    SCRIPT="${BINPATH}/${MINUS_EXT}"

    if [ ! -f $SCRIPT ]; then   
            ln -s ${ABSOLUTEPATH} ${SCRIPT};
            printf "${CYAN}Linked %-50s ${ORANGE} --> ${GREEN} %-6s ${NC}\n" "${SCRIPT}" "${ABSOLUTEPATH}";
        else
            # printf "${ORANGE}Link already created for %-50s ${NC}\n" "${SCRIPT}"
    fi
done